kind: pipeline
type: docker
name: dorganize

steps:
- name: dokku deploy
  image: appleboy/drone-git-push
  volumes:
    - name: ssh
      path: /root/.ssh
  settings:
    branch: master
    remote: ssh://dokku@dokku.bitcore.nz/dorganizer
    force: false
    commit: true

trigger:
  branch:
  - main

volumes:
  - name: ssh
    host:
      path: /home/drone/.ssh