"""empty message

Revision ID: 706906f07f7d
Revises: 
Create Date: 2020-10-16 01:04:36.378976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706906f07f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
